source: geolocation
filename: olist_geolocation_dataset.csv

columns:

  - name: geolocation_zip_code_prefix
    type: INTEGER
    nullable: false

  - name: geolocation_lat
    type: NUMERIC
    nullable: true

  - name: geolocation_lng
    type: NUMERIC
    nullable: true

  - name: geolocation_city
    type: STRING
    nullable: true

  - name: geolocation_state
    type: STRING
    nullable: true